# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'
 source 'https://github.com/CocoaPods/Specs.git'
 source 'https://cdn.cocoapods.org/'

target 'ConsumerSampleSdk' do
   use_frameworks!
   pod 'ContactoSDK', '~> 1.0.4-beta'
end
